services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: seller_system_sql
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    networks:
      - seller-network
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Password123! -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 10s
    volumes:
      - sql_data:/var/opt/mssql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: seller_system_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - seller-network  
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    container_name: seller_system_api
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SellerDb;User Id=sa;Password=Password123!;TrustServerCertificate=True;
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
    ports:
      - "5000:8080"
    networks:
      - seller-network
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: src/Worker/Dockerfile
    container_name: seller_system_worker
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SellerDb;User Id=sa;Password=Password123!;TrustServerCertificate=True;
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
    networks:
      - seller-network
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  blazor:
    build:
      context: .
      dockerfile: src/BlazorApp/Dockerfile
    container_name: seller_system_blazor
    environment:
      - ApiBaseUrl=http://api:8080
    ports:
      - "5002:8080"
    networks:
      - seller-network
    depends_on:
      api:
        condition: service_started

volumes:
  sql_data:
  rabbitmq_data:

networks:
  seller-network:
    driver: bridge